name: Build RolandESPMaus Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with ESP-IDF v4.4 (pinned)
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4

      - name: Configure & build
        run: |
          idf.py set-target esp32
          idf.py reconfigure
          idf.py build

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RolandESPMaus_firmware
          path: |
            build/*.bin
            build/*.elf
            build/flasher_args.json
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
