name: ESP32 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ESP-IDF environment
        uses: espressif/setup-esp-idf@v1
        with:
          version: v4.4
          target: esp32

      - name: Configure project
        run: idf.py set-target esp32

      - name: Build project
        run: idf.py build

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: RolandESPMaus-firmware
          path: build/*.bin
